#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: setup_provider.sh --base-url URL [options]

Options:
  --base-url URL             OpenAI-compatible endpoint (required)
  --alias NAME               Command/profile alias (default: alt)
  --provider-id NAME         Codex provider ID (default: alias)
  --api-key-file FILE        Existing key file; it will be chmod 600
  --api-key-stdin            Read one key line from stdin (not shell history)
  --model MODEL              Alternate model (required)
  --reasoning-effort VALUE   Alternate reasoning effort (default: high)
  --wire-api VALUE           Codex wire API: responses or chat (default: responses)
  --codex-home DIR           Codex home (default: $CODEX_HOME or ~/.codex)
  --wrapper FILE              Wrapper destination (default: ~/.local/bin/codex)
  --help                     Show this help

If no key source is supplied, an interactive hidden prompt is used.
EOF
  exit 2
}

die() { echo "setup_provider: $*" >&2; exit 1; }

base_url=""
alias_name="alt"
provider_id=""
key_file=""
key_from_stdin=0
model=""
reasoning_effort="high"
wire_api="responses"
codex_home="${CODEX_HOME:-$HOME/.codex}"
wrapper_path="$HOME/.local/bin/codex"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url) [[ $# -ge 2 ]] || usage; base_url="$2"; shift 2 ;;
    --alias) [[ $# -ge 2 ]] || usage; alias_name="$2"; shift 2 ;;
    --provider-id) [[ $# -ge 2 ]] || usage; provider_id="$2"; shift 2 ;;
    --api-key-file) [[ $# -ge 2 ]] || usage; key_file="$2"; shift 2 ;;
    --api-key-stdin) key_from_stdin=1; shift ;;
    --model) [[ $# -ge 2 ]] || usage; model="$2"; shift 2 ;;
    --reasoning-effort) [[ $# -ge 2 ]] || usage; reasoning_effort="$2"; shift 2 ;;
    --wire-api) [[ $# -ge 2 ]] || usage; wire_api="$2"; shift 2 ;;
    --codex-home) [[ $# -ge 2 ]] || usage; codex_home="$2"; shift 2 ;;
    --wrapper) [[ $# -ge 2 ]] || usage; wrapper_path="$2"; shift 2 ;;
    --help|-h) usage ;;
    *) usage ;;
  esac
done

[[ -n "$base_url" ]] || die "--base-url is required"
[[ "$base_url" =~ ^https://[^\"[:space:]]+$ ]] || die "--base-url must be an https URL without quotes or spaces"
[[ "$alias_name" =~ ^[A-Za-z0-9_-]+$ ]] || die "alias contains unsupported characters"
provider_id="${provider_id:-$alias_name}"
[[ "$provider_id" =~ ^[A-Za-z0-9_-]+$ ]] || die "provider ID contains unsupported characters"
[[ -n "$model" ]] || die "--model is required"
[[ "$model" =~ ^[A-Za-z0-9._:/-]+$ ]] || die "model contains unsupported characters"
[[ "$reasoning_effort" =~ ^[A-Za-z0-9._:-]+$ ]] || die "reasoning effort contains unsupported characters"
[[ "$wire_api" =~ ^(responses|chat)$ ]] || die "wire API must be responses or chat"

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
codex_home="$(mkdir -p -- "$codex_home" && cd -- "$codex_home" && pwd -P)"
base_config="$codex_home/config.toml"
profile_config="$codex_home/${alias_name}.config.toml"
restore_dir="$codex_home/provider-bridge-restore"
bridge_config="$codex_home/provider-bridge.env"

if [[ -n "$key_file" ]]; then
  [[ -f "$key_file" ]] || die "key file does not exist: $key_file"
  key_file="$(cd -- "$(dirname -- "$key_file")" && pwd -P)/$(basename -- "$key_file")"
  chmod 600 -- "$key_file"
else
  key_file="$codex_home/${alias_name}-api-key"
  umask 077
  if (( key_from_stdin )); then
    IFS= read -r key_value || true
  else
    [[ -t 0 ]] || die "non-interactive setup needs --api-key-file or --api-key-stdin"
    printf 'Alternate provider API key (hidden): ' >&2
    IFS= read -r -s key_value || true
    printf '\n' >&2
  fi
  [[ -n "${key_value:-}" ]] || die "empty API key"
  key_tmp="$(mktemp "$codex_home/.${alias_name}-api-key.XXXXXX")"
  chmod 600 -- "$key_tmp"
  printf '%s\n' "$key_value" > "$key_tmp"
  unset key_value
  mv -- "$key_tmp" "$key_file"
fi

mkdir -p -- "$restore_dir"
chmod 700 -- "$restore_dir"

[[ "$key_file" != *'"'* && "$key_file" != *'\\'* ]] || die "key path cannot contain quotes or backslashes"

profile_tmp="$(mktemp "$codex_home/.${alias_name}.config.XXXXXX")"
chmod 600 -- "$profile_tmp"
cat > "$profile_tmp" <<EOF
# Generated by codex-provider-bridge. The key is read from a mode-600 file.
model = "$model"
model_provider = "$provider_id"
model_reasoning_effort = "$reasoning_effort"

[model_providers.$provider_id]
name = "$provider_id"
base_url = "$base_url"
wire_api = "$wire_api"
requires_openai_auth = false
request_max_retries = 2
stream_max_retries = 2
stream_idle_timeout_ms = 300000

[model_providers.$provider_id.auth]
command = "/usr/bin/cat"
args = ["$key_file"]
refresh_interval_ms = 300000
timeout_ms = 5000

[features]
apps = false
EOF
mv -- "$profile_tmp" "$profile_config"

if [[ ! -f "$base_config" ]]; then
  umask 077
  : > "$base_config"
fi
provider_pattern="^\\[model_providers\\.${provider_id}\\][[:space:]]*$"
if command -v rg >/dev/null 2>&1; then
  provider_exists=0
  rg -q "$provider_pattern" "$base_config" 2>/dev/null || provider_exists=$?
else
  provider_exists=0
  grep -Eq "$provider_pattern" "$base_config" 2>/dev/null || provider_exists=$?
fi
if [[ "$provider_exists" -ne 0 ]]; then
  base_tmp="$(mktemp "$codex_home/.config.toml.XXXXXX")"
  chmod 600 -- "$base_tmp"
  cat "$base_config" > "$base_tmp"
  cat >> "$base_tmp" <<EOF

# Provider definition kept in the base config so VS Code can open an alternate-provider thread.
# The base default provider/model above remains unchanged.
[model_providers.$provider_id]
name = "$provider_id"
base_url = "$base_url"
wire_api = "$wire_api"
requires_openai_auth = false
request_max_retries = 2
stream_max_retries = 2
stream_idle_timeout_ms = 300000

[model_providers.$provider_id.auth]
command = "/usr/bin/cat"
args = ["$key_file"]
refresh_interval_ms = 300000
timeout_ms = 5000
EOF
  mv -- "$base_tmp" "$base_config"
else
  echo "Existing [model_providers.$provider_id] kept; verify its base_url/model auth path." >&2
fi

bridge_tmp="$(mktemp "$codex_home/.provider-bridge.env.XXXXXX")"
chmod 600 -- "$bridge_tmp"
cat > "$bridge_tmp" <<EOF
# Non-secret bridge settings read by the wrapper.
BRIDGE_ALIAS="$alias_name"
BRIDGE_PROVIDER="$provider_id"
BRIDGE_PROFILE="$alias_name"
EOF
mv -- "$bridge_tmp" "$bridge_config"

mkdir -p -- "$(dirname -- "$wrapper_path")"
if [[ -e "$wrapper_path" ]]; then
  backup_path="$wrapper_path.bak.$(date +%Y%m%d%H%M%S)"
  mv -- "$wrapper_path" "$backup_path"
  echo "Existing wrapper backed up to $backup_path" >&2
fi
install -m 700 -- "$script_dir/codex_provider_wrapper.sh" "$wrapper_path"

echo "Configured alternate profile at $profile_config" >&2
echo "Installed wrapper at $wrapper_path" >&2
echo "Ensure $(dirname -- "$wrapper_path") is before the VS Code extension binary in PATH." >&2
